const router = require("express")()

const { Track, DedicateList } = require('../../BusinessLogic') 

/**
 * @swagger
 *
 * /dedicate/track:
 *   post:
 *     tags: ["api"]
 *     summary: Dedicate or request track with or without message
 *     consumes:
 *       - application/json 
 *     produces:
 *       - application/json
 *     parameters:
 *     - in: body
 *       name: body
 *       schema:
 *         type: object
 *         required:
 *           - track_id
 *         properties:
 *           track_id:
 *             type: integer
 *             example: 5
 *           message:
 *             type: object
 *             properties:
 *               content:
 *                 type: string
 *                 minLength: 0
 *                 maxLength: 200
 *                 example: A sentence of about 200 characters Max 
 *               name:
 *                 type: string
 *                 minLength: 0
 *                 maxLength: 50
 *                 example: Sender Name
 *     responses:
 *       400:
 *         description: Invalid input error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/response_errors/400'
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/response_errors/500'
 *       200:
 *         description: when dedication is successful, Song Dedication Id generated by default, Message Id is generated only if message is present
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 dl_id:
 *                   type: integer
 *                   example: 34
 *                 msg_id:
 *                   type: integer
 *                   example: 24
 */
router.post('/track', async (req, res)=>{
    console.log(req.body)
    let track_id = req.body.track_id
    let message = req.body.message
    try{
        if(!track_id || isNaN(track_id)){
            res.status(400).json({ error: "Track ID is must and should be a number"})
            return
        }

        if(message && message.content){
            if(!(message.content && message.name)){
                res.status(400).json({ error: "Message sender name and content both must present" })
                return
            }
        }

        // check this track is already played one hour before
        let { status, track_path } = await DedicateList.checkTrackPlayed(track_id)

        if(status){
            res.status(409).json({ error: "Sorry, The selected track has already been played. Try again after one hour !!!" })
            return
        }        

        // if not played add to the dedicatelist and add message if present
        let { dl_id, msg_id } = await DedicateList.addTrack({track_id, track_path}, message)

        res.status(200).json({ dl_id, msg_id })
        Track.getAndSetCurrentTrackInfo()
    }catch(err){
        res.status(500).json({ error:'Internal Server Error', actualErr: err })
    }
})

/**
 * @swagger
 *
 * /dedicate/message:
 *   post:
 *     tags: ["api"]
 *     summary: Send message without dedication track
 *     consumes:
 *       - application/json 
 *     parameters:
 *     - in: "body"
 *       name: "body"
 *       schema:
 *         type: object
 *         required:
 *           - content
 *           - name
 *         properties:
 *           content:
 *             type: string
 *             minLength: 0
 *             maxLength: 200
 *             example: A sentence of about 200 characters Max
 *           name:
 *             type: string
 *             minLength: 0
 *             maxLength : 50
 *             example: Sender Name
 *     responses:
 *       400:
 *         description: Invalid input error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/response_errors/400'
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/response_errors/500'
 *       200:
 *         description: "After successful"
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 msg:
 *                   type: string
 *                   example: Posted Successfully
 */
router.post('/message', async (req, res)=>{
    let message = req.body
    try{
        if(!(message && message.content && message.name)){
            res.status(400).json({ error: "Message sender name and content both must present" })
            return
        }

        message.displayTime = 5000
        message.isDedicated = false
        console.log({message})
        io.sockets.emit('message', message)

        res.status(200).json({ msg: "Posted Successfully" })
    }catch(err){
        res.status(500).json({ error:'Internal Server Error', actualErr: err })
    }
})

module.exports = router